### ISSUE TITLE
Syntax suggestion

### ISSUE THREAD

**Issue by robertmartin8** [Shawn-Shan/eru#1]
I've been coding in python for quite a while now, but I've never come across the following syntax:

```python
x = GRU(10, 128, return_sequence=False)(input) 
x = Dense(128, 10)(x)
x = Activation("softmax")(x)
```

What does it do?

By the way, I really like the idea of this project: PyTorch needs some abstraction to make it as usable as keras. I'd like to contribute at some stage. Just FYI, there's a similar sounding project called (torchsample)[https://github.com/ncullen93/torchsample] remove the need for a lot of PyTorch boilerplate. 

(nice Silmarillion reference)

**Comment by Shawn-Shan** [comment]
Thanks for the feedback and interests in contributing. The syntax is similar to Keras framework and we can change it if people find it hard to use. 

I added a [CONTRIBUTING.md](https://github.com/Shawn-Shan/eru/blob/master/CONTRIBUTING.md) recently and you can join our [slack channel](https://join.slack.com/t/eru-framework/shared_invite/enQtMzU0NjY2NjI0NTYxLTAzN2YwOThmNzQ1MzBjZDU4MWRhMjFjMzNmNTkxZDMzZDIxZGQzZWZiNmE0MzI0MzVjN2ZhMWNiYWJiMzI4OTI) for more information about contributing.
